### ISSUE TITLE
Getting 500 internal server errors at random

### ISSUE THREAD

**Issue by guysoft** [jpetrucciani/hubspot3#25]
Seems to have happened since hubspot had their outage
reproduce:
```
 engagements_client = EngagementsClient(api_key=api)

 # Handle offset
 print("Getting list of all engagements")

 engagements = engagements_client.get_all()
```

output (I checked, that status is indeed 500):

```
Getting list of all engagements
Traceback (most recent call last):
 File "/opt/shapedo/sales/hubspot/get_all_data.py", line 36, in 
 get_all_engagements(os.path.join(args.folder, 'hubspot_engagements.json'), API)
 File "/opt/shapedo/sales/hubspot/engagements.py", line 12, in get_all_engagements
 engagements = engagements_client.get_all()
 File "/usr/local/lib/python3.6/dist-packages/hubspot3/engagements.py", line 73, in get_all
 **options
 File "/usr/local/lib/python3.6/dist-packages/hubspot3/base.py", line 361, in _call
 **options
 File "/usr/local/lib/python3.6/dist-packages/hubspot3/base.py", line 261, in _call_raw
 result = self._execute_request_raw(connection, request_info)
 File "/usr/local/lib/python3.6/dist-packages/hubspot3/base.py", line 182, in _execute_request_raw
 raise HubspotServerError(result, request)
hubspot3.error.HubspotServerError: 
internal error

---- request ----
GET api.hubapi.com/engagements/v1/engagements/paged?limit=250&offset=655163296&hapikey=xxxxxx, [timeout= ]

---- body ----

---- headers ----

---- result ----

---- body -----
{"status":"error","message":"internal error","correlationId":"9df8fff4-739f-4e3a-bb2e-b8e539ddf136","requestId":"c69f7fd841bf5bcc064aebbeab45b65f"}

---- headers -----

---- reason ----
Internal Server Error

---- trigger error ----

```

using ``hubspot3==3.2.3``

**Comment by guysoft** [comment]
Ok, solved by doing:
```
engagements = engagements_client.get_all(number_retries=6)
```

I recommend adding 1 or 2 retries, because it seems like hubspot is giving internal server errors.
